openapi: 3.0.2
info:
    title: Block Storage API Product
    description: Block Storage API Product Documentation
    contact:
        name: Tribo IAAS Cloud
        url: https://github.com/luizalabs
        email: lia.furtado@luizalabs.com
    version: 1.52.0
paths:
    /v0/healthcheck:
        get:
            tags:
            - healthchecks
            summary: Healthcheck
            description: Check api status
            operationId: healthcheck_v0_healthcheck_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Healthcheck'
            security:
            -   OAuth2:
                - block-storage.read
    /v0/volume_types:
        get:
            tags:
            - volume-types
            summary: List Volume Types
            description: Returns a list of volume types
            operationId: list_volume_types_v0_volume_types_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeTypeList'
            security:
            -   OAuth2:
                - block-storage.read
        post:
            tags:
            - volume-types
            summary: Create Volume Type
            description: Create volume type only in DB
            operationId: create_volume_type_v0_volume_types_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VolumeTypeRequest'
                required: true
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IdResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
    /v0/volume_types_all:
        get:
            tags:
            - volume-types
            summary: List Volume Types All
            description: Returns a list of all volume types from db
            operationId: list_volume_types_all_v0_volume_types_all_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeTypeDbListResponse'
            security:
            -   OAuth2:
                - block-storage.read
    /v0/usage:
        get:
            tags:
            - usage
            summary: Get Usage
            description: Retrieve usage for specific quota_slug (disk & volumes)
            operationId: get_usage_v0_usage_get
            parameters:
            -   description: quota_slug
                required: false
                schema:
                    title: Quota Slug
                    type: string
                    format: string
                name: quota_slug
                in: query
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListUsageResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.read
    /v0/snapshots:
        get:
            tags:
            - snapshots
            summary: List snapshots
            description: List snapshots
            operationId: list_snapshots_v0_snapshots_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListSnapshotResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.read
        post:
            tags:
            - snapshots
            summary: Create snapshot
            description: Create snapshot
            operationId: create_snapshot_v0_snapshots_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SnapshotCreateRequest'
                required: true
            responses:
                '202':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeCreateResponse'
                    links:
                        delete:
                            operationId: delete_snapshot_v0_snapshots__snapshot_id__delete
                            description: Delete snapshot
                            parameters:
                                snapshot_id: $response.body#/id
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
    /v0/snapshots/{snapshot_id}:
        post:
            tags:
            - snapshots
            summary: Restore Snapshot
            description: Restore a snapshot
            operationId: restore_snapshot_v0_snapshots__snapshot_id__post
            parameters:
            -   description: snapshot_id
                required: true
                schema:
                    title: Snapshot Id
                    type: string
                    format: uuid
                name: snapshot_id
                in: path
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RestoreSnapshotRequest'
                required: true
            responses:
                '202':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeCreateResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
        delete:
            tags:
            - snapshots
            summary: Delete Snapshot
            description: Delete a snapshot from the provided tenant_id
            operationId: delete_snapshot_v0_snapshots__snapshot_id__delete
            parameters:
            -   description: snapshot_id
                required: true
                schema:
                    title: Snapshot Id
                    type: string
                    format: uuid
                name: snapshot_id
                in: path
            responses:
                '204':
                    description: Successful Response
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
    /v0/volumes:
        get:
            tags:
            - block-storage
            summary: List Volumes
            description: Returns a list of volumes from the provided tenant_id
            operationId: list_volumes_v0_volumes_get
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeListResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.read
            x-cli-description: List all Block Storage volumes
        post:
            tags:
            - block-storage
            summary: Create Volume
            description: Create a volume for a provided tenant_id
            operationId: create_volume_v0_volumes_post
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VolumeCreateRequest'
                required: true
            responses:
                '201':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeCreateResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
                '200':
                    links:
                        read:
                            operationId: volume_details_v0_volumes__id__get
                            description: Read Block Storage volume
                            parameters:
                                id: $response.body#/id
                        update:
                            operationId: update_volume_v0_volumes__id__patch
                            description: Update Block Storage volume
                            parameters:
                                id: $response.body#/id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $response.body#/id
            security:
            -   OAuth2:
                - block-storage.write
            x-cli-description: Create a Block Storage volume
    /v0/volumes/{id}:
        get:
            tags:
            - block-storage
            summary: Volume Details
            description: Returns a volume details from the provided tenant_id
            operationId: volume_details_v0_volumes__id__get
            parameters:
            -   description: id
                required: true
                schema:
                    title: Volume Id
                    type: string
                    format: uuid
                name: id
                in: path
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeResponse'
                    links:
                        update:
                            operationId: update_volume_v0_volumes__id__patch
                            description: Update Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.read
            x-cli-description: Get a Block Storage volume details
        delete:
            tags:
            - block-storage
            summary: Delete Volume
            description: Delete a volume from the provided tenant_id
            operationId: delete_volume_v0_volumes__id__delete
            parameters:
            -   description: id
                required: true
                schema:
                    title: Volume Id
                    type: string
                    format: uuid
                name: id
                in: path
            -   description: force
                required: false
                schema:
                    title: Force
                    type: boolean
                    default: false
                name: force
                in: query
            responses:
                '204':
                    description: Successful Response
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
            x-cli-description: Delete a Block Storage volume
        patch:
            tags:
            - block-storage
            summary: Update Volume
            description: Update a volume's name from the provided tenant_id
            operationId: update_volume_v0_volumes__id__patch
            parameters:
            -   description: id
                required: true
                schema:
                    title: Volume Id
                    type: string
                    format: uuid
                name: id
                in: path
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VolumeUpdateRequest'
                required: true
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeResponse'
                    links:
                        read:
                            operationId: volume_details_v0_volumes__id__get
                            description: Read Block Storage volume
                            parameters:
                                id: $request.path.id
                        delete:
                            operationId: delete_volume_v0_volumes__id__delete
                            description: Delete Block Storage volume
                            parameters:
                                id: $request.path.id
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
            x-cli-description: Update a Block Storage volume
    /v0/volumes/{id}/attach/{virtual_machine_id}:
        post:
            tags:
            - block-storage
            summary: Attach Volume
            description: Attach a volume into an instance, both from the provided
                tenant_id
            operationId: attach_volume_v0_volumes__id__attach__virtual_machine_id__post
            parameters:
            -   description: id
                required: true
                schema:
                    title: Volume Id
                    type: string
                    format: uuid
                name: id
                in: path
            -   description: virtual_machine_id
                required: true
                schema:
                    title: Virtual Machine Id
                    type: string
                    format: uuid
                name: virtual_machine_id
                in: path
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeResponse'
                    links:
                        delete:
                            description: Detach from a Virtual Machine instance
                            operationId: detach_volume_v0_volumes__id__detach__virtual_machine_id__post
                            parameters:
                                id: $path.id
                        read:
                            description: Check if block storage is attached to Virtual
                                Machine instance
                            operationId: volume_details_v0_volumes__id__get
                            parameters:
                                id: $path.id
                            x-cli-wait-termination:
                                maxRetries: 2
                                intervalInSeconds: 15s
                                jsonPathQuery: $.result.attachments[*]
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
            x-cli-name: attach
    /v0/volumes/{id}/detach/{virtual_machine_id}:
        post:
            tags:
            - block-storage
            summary: Detach Volume
            description: 'Detaches a volume from an instance. Make sure to unmount

                any file systems on the device within your operating system before

                detaching the volume. Failure to do so can result in the volume

                becoming stuck in the busy state while detaching. If this happens,

                detachment can be delayed indefinitely until you unmount the volume,

                force detachment, reboot the instance, or all three.'
            operationId: detach_volume_v0_volumes__id__detach__virtual_machine_id__post
            parameters:
            -   description: id
                required: true
                schema:
                    title: Volume Id
                    type: string
                    format: uuid
                name: id
                in: path
            -   description: virtual_machine_id
                required: true
                schema:
                    title: Virtual Machine Id
                    type: string
                    format: uuid
                name: virtual_machine_id
                in: path
            -   description: force
                required: false
                schema:
                    title: Force
                    type: boolean
                    default: false
                name: force
                in: query
            responses:
                '200':
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VolumeResponse'
                '422':
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HTTPValidationError'
            security:
            -   OAuth2:
                - block-storage.write
            x-cli-name: detach
components:
    schemas:
        AttachmentResponse:
            title: AttachmentResponse
            required:
            - virtual_machine_id
            type: object
            properties:
                virtual_machine_id:
                    title: Virtual Machine Id
                    type: string
                    format: uuid
            example:
                virtual_machine_id: 9f1732cc-a2c9-4471-af68-479adf91e49b
        HTTPValidationError:
            title: HTTPValidationError
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            example:
                message: Unauthorized
                slug: Unauthorized
        Healthcheck:
            title: Healthcheck
            required:
            - status
            type: object
            properties:
                status:
                    title: Status
                    type: string
            example:
                status: OK
        IdResponse:
            title: IdResponse
            required:
            - id
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
            example:
                id: 9f1732cc-a2c9-4471-af68-479adf91e49b
        QosSpecs:
            title: QosSpecs
            required:
            - name
            - consumer
            type: object
            properties:
                name:
                    title: Name
                    type: string
                consumer:
                    title: Consumer
                    type: string
                specs:
                    title: Specs
        ValidationError:
            title: ValidationError
            required:
            - loc
            - msg
            - type
            type: object
            properties:
                message:
                    title: Message
                    type: string
                slug:
                    title: Slug
                    type: string
            example:
                message: Unauthorized
                slug: Unauthorized
        VolumeCreateRequest:
            title: VolumeCreateRequest
            required:
            - name
            - size
            - volume_type
            - description
            type: object
            properties:
                name:
                    title: Name
                    type: string
                size:
                    title: Size
                    type: integer
                    description: Gibibytes (GiB)
                volume_type:
                    title: Volume Type
                    type: string
                description:
                    title: Description
                    type: string
            example:
                name: volume name
                size: 10
                volume_type: rbd
                description: volume description
        VolumeCreateResponse:
            title: VolumeCreateResponse
            required:
            - id
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
            example:
                id: 9f1732cc-a2c9-4471-af68-479adf91e49b
        VolumeListResponse:
            title: VolumeListResponse
            required:
            - volumes
            type: object
            properties:
                volumes:
                    title: Volumes
                    type: array
                    items:
                        $ref: '#/components/schemas/VolumeResponse'
            example:
                volumes:
                -   id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                    volume_id: 9f2310ac-1944-41e8-85ff-b5671b00c820
                    status: in-use
                    error: some error description or null
                    size: 10
                    name: volume name
                    volume_type:
                        name: rbd
                        sku: sku1234
                    description: volume description
                    attachments:
                    -   virtual_machine_id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                    created_at: '2022-01-01T00:00:00Z'
                    updated_at: '2022-01-01T00:00:00Z'
        VolumeResponse:
            title: VolumeResponse
            required:
            - id
            - volume_id
            - status
            - error
            - size
            - name
            - volume_type
            - description
            - created_at
            - updated_at
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
                volume_id:
                    title: Id
                    type: string
                    format: uuid
                status:
                    title: Status
                    type: string
                error:
                    title: Error
                    type: string
                size:
                    title: Size
                    type: integer
                    description: Gibibytes (GiB)
                name:
                    title: Name
                    type: string
                volume_type:
                    $ref: '#/components/schemas/VolumeTypeResponseForVolume'
                description:
                    title: Description
                    type: string
                attachments:
                    title: Attachments
                    type: array
                    items:
                        $ref: '#/components/schemas/AttachmentResponse'
                created_at:
                    title: Created At
                    type: string
                    format: date-time
                updated_at:
                    title: Updated At
                    type: string
                    format: date-time
            example:
                id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                volume_id: 9f2310ac-1944-41e8-85ff-b5671b00c820
                status: in-use
                error: some error description or null
                size: 10
                name: volume name
                volume_type:
                    name: rbd
                    sku: sku1234
                description: volume description
                attachments:
                -   virtual_machine_id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                created_at: '2022-01-01T00:00:00Z'
                updated_at: '2022-01-01T00:00:00Z'
        VolumeTypeDbListResponse:
            title: VolumeTypeDbListResponse
            required:
            - types
            type: object
            properties:
                types:
                    title: Types
                    type: array
                    items:
                        $ref: '#/components/schemas/VolumeTypeDbResponse'
            example:
                types:
                -   id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                    sku: sku1234
                    name: some_name
                    internal: true
        VolumeTypeDbResponse:
            title: VolumeTypeDbResponse
            required:
            - id
            - name
            - sku
            - internal
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
                name:
                    title: Name
                    type: string
                sku:
                    title: Sku
                    type: string
                internal:
                    title: Internal
                    type: boolean
        VolumeTypeList:
            title: VolumeTypeList
            required:
            - types
            type: object
            properties:
                types:
                    title: Types
                    type: array
                    items:
                        $ref: '#/components/schemas/VolumeTypeResponse'
            example:
                types:
                -   id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                    name: rbd
                    description: volume type description
                    sku: sku1234
                    qos_specs:
                        name: teste-qos-high-iops
                        consumer: front-end
                        specs:
                            total_iops_sec: '1000'
        VolumeTypeRequest:
            title: VolumeTypeRequest
            required:
            - name
            - sku
            - internal
            type: object
            properties:
                name:
                    title: Name
                    type: string
                sku:
                    title: Sku
                    type: string
                internal:
                    title: Internal
                    type: boolean
            example:
                name: rbd
                sku: sku1234
                internal: true
        VolumeTypeResponse:
            title: VolumeTypeResponse
            required:
            - id
            - name
            - sku
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
                name:
                    title: Name
                    type: string
                description:
                    title: Description
                    type: string
                sku:
                    title: Sku
                    type: string
                qos_specs:
                    $ref: '#/components/schemas/QosSpecs'
            example:
                id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                name: rbd
                description: volume type description
                sku: sku1234
                qos_specs:
                    name: teste-qos-high-iops
                    consumer: front-end
                    specs:
                        total_iops_sec: '1000'
        VolumeTypeResponseForVolume:
            title: VolumeTypeResponseForVolume
            required:
            - name
            - sku
            type: object
            properties:
                name:
                    title: Name
                    type: string
                sku:
                    title: Sku
                    type: string
            example:
                name: rbd
                description: volume type description
                sku: sku1234
        VolumeUpdateRequest:
            title: VolumeUpdateRequest
            required:
            - name
            type: object
            properties:
                name:
                    title: Name
                    type: string
            example:
                name: new volume name
        SnapshotResponse:
            title: SnapshotResponse
            required:
            - id
            - created_at
            - name
            - description
            - volume_id
            - status
            - size
            - progress
            type: object
            properties:
                id:
                    title: Id
                    type: string
                    format: uuid
                created_at:
                    title: Created At
                    type: string
                    format: date-time
                name:
                    title: Name
                    type: string
                description:
                    title: Description
                    type: string
                volume_id:
                    title: Id
                    type: string
                    format: uuid
                status:
                    title: Status
                    type: string
                size:
                    title: Size
                    type: integer
                    description: Gibibytes (GiB)
                progress:
                    title: Progress
                    type: string
                    description: Porcentagem
            example:
                id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                created_at: '2022-01-01T00:00:00Z'
                name: some_name
                description: some_description
                volume_id: 00000000-0000-0000-0000-000000000000
                status: available
                size: 10
                progress: 100%
        ListSnapshotResponse:
            title: ListSnapshotResponse
            required:
            - results
            type: object
            properties:
                results:
                    title: snapshots
                    type: array
                    items:
                        $ref: '#/components/schemas/SnapshotResponse'
            example:
                results:
                -   id: 9f1732cc-a2c9-4471-af68-479adf91e49b
                    created_at: '2022-01-01T00:00:00Z'
                    name: some_name
                    description: some_description
                    volume_id: 00000000-0000-0000-0000-000000000000
                    status: available
                    size: 10
                    progress: 100%
        SnapshotCreateRequest:
            title: SnapshotCreateRequest
            required:
            - volume_id
            - name
            - description
            type: object
            properties:
                volume_id:
                    title: Id
                    type: string
                    format: uuid
                name:
                    title: Name
                    type: string
                description:
                    title: Description
                    type: string
            example:
                volume_id: 00000000-0000-0000-0000-000000000000
                name: snapshot name
                description: snapshot description
        RestoreSnapshotRequest:
            title: RestoreSnapshotRequest
            required:
            - name
            - description
            type: object
            properties:
                name:
                    title: Name
                    type: string
                description:
                    title: Description
                    type: string
            example:
                name: snapshot name
                description: snapshot description
        GetUsageResponse:
            title: RestoreSnapshotRequest
            required:
            - quota_slug
            - used
            type: object
            properties:
                quota_slug:
                    title: Quota Slug
                    type: string
                used:
                    title: Used
                    type: integer
            example:
                quota_slug: disk
                used: 10
        ListUsageResponse:
            title: ListUsageResponse
            required:
            - results
            type: object
            properties:
                results:
                    title: results
                    type: array
                    items:
                        $ref: '#/components/schemas/GetUsageResponse'
            example:
                results:
                -   quota_slug: disk
                    used: 10
    securitySchemes:
        OAuth2:
            flows:
                authorizationCode:
                    authorizationUrl: https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/auth
                    tokenUrl: https://idp-maas-sandbox.ipet.sh/auth/realms/master/protocol/openid-connect/token
                    scopes:
                        block-storage.read: Ler informações de recursos IaaS
                        block-storage.write: Escrever informações de recursos IaaS
            type: oauth2
            description: OAuth2 via IDPA
tags:
-   name: healthchecks
    description: healthchecks
    x-cli-hidden: true
-   name: usage
    description: usage
-   name: snapshots
    description: snapshots
-   name: volume-types
    description: volume types
-   name: block-storage
    description: block storage
    x-cli-description: Block Storage Volume Resources
    x-cli-name: volume
servers:
-   url: https://api-block-storage{env}.{region}.jaxyendy.com
    variables:
        region:
            description: Region to reach the service
            default: br-ne-1
            enum:
            - br-ne-1
            - br-ne-2
            - br-se-1
        env:
            description: Environment to use
            default: ''
            enum:
            - ''
            - .pre-prod
            x-cli-transforms:
            -   type: translate
                translations:
                -   from: prod
                    to: ''
                -   from: pre-prod
                    to: .pre-prod
$id: https://block-storage.jaxyendy.com/openapi.json
