{
  "openapi": "3.1.0",
  "info": {
    "title": "Magalu Cloud IAM",
    "description": "The Magalu Cloud IAM.",
    "version": "0.1.0"
  },
  "paths": {
    "/api/v1/healthcheck": {
      "get": {
        "tags": [
          "Healthcheck"
        ],
        "summary": "Healthcheck",
        "operationId": "healthcheck_api_v1_healthcheck_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "x-mgc-hidden": true
      }
    },
    "/api/v1/members": {
      "get": {
        "tags": [
          "Members"
        ],
        "summary": "Get Members",
        "operationId": "get_members_api_v1_members_get",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Email"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Member"
                  },
                  "title": "Response Get Members Api V1 Members Get"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Members"
        ],
        "summary": "Add Member",
        "operationId": "add_member_api_v1_members_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateMember"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Member"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/members/{uuid}": {
      "delete": {
        "tags": [
          "Members"
        ],
        "summary": "Remove Member",
        "operationId": "remove_member_api_v1_members__uuid__delete",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Uuid",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/members/{uuid}/grants": {
      "get": {
        "tags": [
          "Members"
        ],
        "summary": "Get Grants",
        "operationId": "get_grants_api_v1_members__uuid__grants_get",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Uuid",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Privileges"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Members"
        ],
        "summary": "Add Grants",
        "operationId": "add_grants_api_v1_members__uuid__grants_patch",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Uuid",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EditGrant"
              }
            }
          },
          "required": true
        },
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/roles": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get Roles",
        "operationId": "get_roles_api_v1_roles_get",
        "parameters": [
          {
            "name": "hidden_permissions",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Hidden Permissions",
              "default": true
            }
          },
          {
            "name": "role_name",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Role Name"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Role"
                  },
                  "title": "Response Get Roles Api V1 Roles Get"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Roles"
        ],
        "summary": "Create Role",
        "operationId": "create_role_api_v1_roles_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRole"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Role"
                  },
                  "title": "Response Create Role Api V1 Roles Post"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/roles/{role_name}": {
      "delete": {
        "tags": [
          "Roles"
        ],
        "summary": "Remove Role",
        "operationId": "remove_role_api_v1_roles__role_name__delete",
        "parameters": [
          {
            "name": "role_name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Role Name"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/roles/{role_name}/permissions": {
      "patch": {
        "tags": [
          "Roles"
        ],
        "summary": "Edit Permissions",
        "operationId": "edit_permissions_api_v1_roles__role_name__permissions_patch",
        "parameters": [
          {
            "name": "role_name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Role Name"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/EditPermissions"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Role"
                  },
                  "title": "Response Edit Permissions Api V1 Roles  Role Name  Permissions Patch"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/roles/{role_name}/members": {
      "get": {
        "tags": [
          "Roles"
        ],
        "summary": "Get Role Members",
        "operationId": "get_role_members_api_v1_roles__role_name__members_get",
        "parameters": [
          {
            "name": "role_name",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Role Name"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/RolesMember"
                  },
                  "title": "Response Get Role Members Api V1 Roles  Role Name  Members Get"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/permissions": {
      "get": {
        "tags": [
          "Permissions"
        ],
        "summary": "Get Products And Permissions",
        "operationId": "get_products_and_permissions_api_v1_permissions_get",
        "parameters": [
          {
            "name": "product_name",
            "in": "query",
            "required": false,
            "schema": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "title": "Product Name"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Product"
                  },
                  "title": "Response Get Products And Permissions Api V1 Permissions Get"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/access-control": {
      "get": {
        "tags": [
          "Access-Control"
        ],
        "summary": "Get Access Control",
        "operationId": "get_access_control_api_v1_access_control_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessControl"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Access-Control"
        ],
        "summary": "Post Access Control",
        "operationId": "post_access_control_api_v1_access_control_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AccessControlCreate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessControl"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Access-Control"
        ],
        "summary": "Update Access Control",
        "operationId": "update_access_control_api_v1_access_control_patch",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AccessControlStatus"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessControl"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/service-accounts": {
      "get": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Get",
        "operationId": "get_api_v1_service_accounts_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ServiceAccountDetail"
                  },
                  "title": "Response Get Api V1 Service Accounts Get"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Create",
        "operationId": "create_api_v1_service_accounts_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ServiceAccountCreate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServiceAccountDetail"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/service-accounts/{sa_uuid}": {
      "delete": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Remove",
        "operationId": "remove_api_v1_service_accounts__sa_uuid__delete",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Edit",
        "operationId": "edit_api_v1_service_accounts__sa_uuid__patch",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ServiceAccountEdit"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ServiceAccountDetail"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/service-accounts/{sa_uuid}/api-keys": {
      "get": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Get Apikeys",
        "operationId": "get_apikeys_api_v1_service_accounts__sa_uuid__api_keys_get",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/APIKeyServiceAccountDetail"
                  },
                  "title": "Response Get Apikeys Api V1 Service Accounts  Sa Uuid  Api Keys Get"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Create Apikey",
        "operationId": "create_apikey_api_v1_service_accounts__sa_uuid__api_keys_post",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/APIKeyServiceAccountCreate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIKeyServiceAccountDetail"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    },
    "/api/v1/service-accounts/{sa_uuid}/api-keys/{apikey_uuid}": {
      "delete": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Revoke Apikey",
        "operationId": "revoke_apikey_api_v1_service_accounts__sa_uuid__api_keys__apikey_uuid__delete",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          },
          {
            "name": "apikey_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Apikey Uuid",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful Response"
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Service-Accounts"
        ],
        "summary": "Edit Apikey",
        "operationId": "edit_apikey_api_v1_service_accounts__sa_uuid__api_keys__apikey_uuid__patch",
        "parameters": [
          {
            "name": "sa_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Sa Uuid",
              "format": "uuid"
            }
          },
          {
            "name": "apikey_uuid",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Apikey Uuid",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/APIKeyServiceAccountEditInput"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/APIKeyServiceAccountDetail"
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "origin": "permissionsAPI",
                  "permission": "turia_iam_editor",
                  "product": "turiaiam",
                  "message": "User action not authorized for permission turia_iam_editor"
                }
              }
            }
          }
        },
        "security": [
          {
            "OAuth2": [
              "iam:read",
              "iam:write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "APIKeyServiceAccountCreate": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "scopes": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Scopes",
            "default": []
          }
        },
        "title": "APIKeyServiceAccountCreate",
        "required": [
          "name"
        ]
      },
      "APIKeyServiceAccountDetail": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string",
            "title": "Uuid"
          },
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "key_pair_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Key Pair Id"
          },
          "key_pair_secret": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Key Pair Secret"
          },
          "scopes": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Scopes",
            "default": []
          },
          "scopes_pending_approval": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Scopes Pending Approval",
            "default": []
          },
          "start_validity": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Start Validity"
          },
          "end_validity": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "End Validity"
          },
          "revoked_at": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Revoked At"
          },
          "revoked_by": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Revoked By"
          }
        },
        "title": "APIKeyServiceAccountDetail",
        "required": [
          "uuid"
        ]
      },
      "APIKeyServiceAccountEditInput": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "scopes": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Scopes",
            "default": []
          }
        },
        "title": "APIKeyServiceAccountEditInput"
      },
      "AccessControl": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "tenant_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Tenant Id"
          },
          "enabled": {
            "type": "boolean",
            "title": "Enabled",
            "default": false
          }
        },
        "title": "AccessControl"
      },
      "AccessControlCreate": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          }
        },
        "title": "AccessControlCreate"
      },
      "AccessControlStatus": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean",
            "title": "Status"
          }
        },
        "title": "AccessControlStatus",
        "required": [
          "status"
        ]
      },
      "CreateMember": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "title": "Email"
          },
          "roles": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Roles"
          },
          "permissions": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Permissions"
          }
        },
        "title": "CreateMember",
        "required": [
          "email"
        ]
      },
      "CreateRole": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "permissions": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Permissions"
          },
          "based_role": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Based Role"
          }
        },
        "title": "CreateRole",
        "required": [
          "name"
        ]
      },
      "EditGrant": {
        "type": "object",
        "properties": {
          "operation": {
            "$ref": "#/components/schemas/OperationType"
          },
          "roles": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Roles",
            "default": []
          },
          "permissions": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Permissions",
            "default": []
          }
        },
        "title": "EditGrant",
        "required": [
          "operation"
        ]
      },
      "EditPermissions": {
        "type": "object",
        "properties": {
          "add": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "title": "Add",
            "default": []
          },
          "remove": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "title": "Remove",
            "default": []
          }
        },
        "title": "EditPermissions"
      },
      "HTTPValidationError": {
        "type": "object",
        "properties": {
          "detail": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "title": "Detail"
          }
        },
        "title": "HTTPValidationError"
      },
      "Member": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string",
            "title": "Uuid",
            "default": ""
          },
          "email": {
            "type": "string",
            "title": "Email",
            "default": ""
          },
          "name": {
            "type": "string",
            "title": "Name",
            "default": ""
          },
          "tenant_id": {
            "type": "string",
            "title": "Tenant Id",
            "default": ""
          },
          "profile": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Profile"
          }
        },
        "title": "Member"
      },
      "OperationType": {
        "type": "string",
        "title": "OperationType",
        "enum": [
          "add",
          "remove"
        ]
      },
      "Permission": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "type": "string",
            "title": "Description"
          }
        },
        "title": "Permission",
        "required": [
          "name",
          "description"
        ]
      },
      "Privileges": {
        "type": "object",
        "properties": {
          "roles": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Roles",
            "default": []
          },
          "permissions": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Permissions",
            "default": []
          }
        },
        "title": "Privileges"
      },
      "Product": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "permissions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Permission"
            },
            "title": "Permissions"
          }
        },
        "title": "Product",
        "required": [
          "name",
          "permissions"
        ]
      },
      "Role": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "origin": {
            "type": "string",
            "title": "Origin"
          },
          "permissions": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Permissions"
          }
        },
        "title": "Role",
        "required": [
          "name"
        ]
      },
      "RolesMember": {
        "type": "object",
        "properties": {
          "member_uuid": {
            "type": "string",
            "title": "Member Uuid"
          },
          "roles": {
            "anyOf": [
              {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              {
                "type": "null"
              }
            ],
            "title": "Roles"
          }
        },
        "title": "RolesMember",
        "required": [
          "member_uuid",
          "roles"
        ]
      },
      "ServiceAccountCreate": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "type": "string",
            "title": "Description"
          },
          "email": {
            "type": "string",
            "title": "Email"
          }
        },
        "title": "ServiceAccountCreate",
        "required": [
          "name",
          "description",
          "email"
        ]
      },
      "ServiceAccountDetail": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string",
            "title": "Uuid"
          },
          "name": {
            "type": "string",
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          },
          "email": {
            "type": "string",
            "title": "Email"
          },
          "tenant": {
            "$ref": "#/components/schemas/Tentant"
          }
        },
        "title": "ServiceAccountDetail",
        "required": [
          "uuid",
          "name",
          "email",
          "tenant"
        ]
      },
      "ServiceAccountEdit": {
        "type": "object",
        "properties": {
          "name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Name"
          },
          "description": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "title": "Description"
          }
        },
        "title": "ServiceAccountEdit"
      },
      "Tentant": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string",
            "title": "Uuid"
          },
          "legal_name": {
            "type": "string",
            "title": "Legal Name"
          }
        },
        "title": "Tentant",
        "required": [
          "uuid",
          "legal_name"
        ]
      },
      "ValidationError": {
        "type": "object",
        "properties": {
          "loc": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          }
        },
        "title": "ValidationError",
        "required": [
          "loc",
          "msg",
          "type"
        ]
      }
    },
    "securitySchemes": {
      "OAuth2": {
        "type": "http",
        "description": "Insira o token JWT com o prefixo 'Bearer '.",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "tags": [
    {
      "name": "Healthcheck",
      "description": "Endpoints para verificação de status e saúde do serviço.",
      "x-mgc-hidden": true
    },
    {
      "name": "Members",
      "description": "Members of Organization."
    },
    {
      "name": "Access-Control",
      "description": "Access control of permissions and roles."
    },
    {
      "name": "Permissions",
      "description": "Permission action of resource."
    },
    {
      "name": "Roles",
      "description": "Roles of organization."
    },
    {
      "name": "Service-Accounts",
      "description": "Service Accounts of organization."
    }
  ]
}